// Vstupní bod knihovny. Komponenty se doplňují po vrstvách podle návrhu;
// zdrojem pravdy je docs/navrh v repozitářích aplikací (PNG + HTML export z Penu).
// Co tu není, pro aplikace neexistuje — nová komponenta se sem přidá ručně.

export { Button } from './components/Buttons/Button'
export type { ButtonProps, ButtonSize, ButtonVariant } from './components/Buttons/Button'
export { IconButton } from './components/Buttons/IconButton'
export type { IconButtonProps } from './components/Buttons/IconButton'

export { Calendar } from './components/Calendar/Calendar'
export type { CalendarProps, CalendarMode } from './components/Calendar/Calendar'
export { DatePresets } from './components/Calendar/DatePresets'
export type { DatePresetsProps, DatePresetOption } from './components/Calendar/DatePresets'
export { TimePicker } from './components/Calendar/TimePicker'
export type { TimePickerProps } from './components/Calendar/TimePicker'

export { FloatingPill } from './components/Cards/FloatingPill'
export type { FloatingPillProps, FloatingPillVariant } from './components/Cards/FloatingPill'
export { GaugeCard } from './components/Cards/GaugeCard'
export type { GaugeCardProps, GaugeCardStat, GaugeCardTone } from './components/Cards/GaugeCard'
export { LabelPreview } from './components/Cards/LabelPreview'
export type { LabelPreviewProps } from './components/Cards/LabelPreview'
export { MediaCard } from './components/Cards/MediaCard'
export type { MediaCardProps } from './components/Cards/MediaCard'
export { NotificationItem, NotificationsPanel } from './components/Cards/NotificationsPanel'
export type {
  NotificationItemProps,
  NotificationsPanelProps,
  NotificationTone,
} from './components/Cards/NotificationsPanel'

export { BarChartHorizontal } from './components/Charts/BarChartHorizontal'
export type {
  BarChartHorizontalProps,
  BarChartHorizontalRow,
} from './components/Charts/BarChartHorizontal'
export { BarChartVertical } from './components/Charts/BarChartVertical'
export type {
  BarChartVerticalProps,
  BarChartVerticalBar,
} from './components/Charts/BarChartVertical'
export { ChartCard } from './components/Charts/ChartCard'
export type { ChartCardProps, ChartTone } from './components/Charts/ChartCard'
export { DonutChart } from './components/Charts/DonutChart'
export type { DonutChartProps, DonutSegment } from './components/Charts/DonutChart'
export { Sparkbars } from './components/Charts/Sparkbars'
export type { SparkbarsProps, SparkbarsBar } from './components/Charts/Sparkbars'
export { StackedBarChart } from './components/Charts/StackedBarChart'
export type {
  StackedBarChartProps,
  StackedBarGroup,
  StackedSegment,
} from './components/Charts/StackedBarChart'

export { Breadcrumbs } from './components/Navigation/Breadcrumbs'
export type { BreadcrumbsProps, BreadcrumbItem } from './components/Navigation/Breadcrumbs'
export { Stepper } from './components/Navigation/Stepper'
export type { StepperProps, StepperStep } from './components/Navigation/Stepper'
export { TabsUnderline } from './components/Navigation/TabsUnderline'
export type { TabsUnderlineProps, TabsUnderlineTab } from './components/Navigation/TabsUnderline'
export { ToolRail } from './components/Navigation/ToolRail'
export type { ToolRailProps, ToolRailItem } from './components/Navigation/ToolRail'
export { TopBar } from './components/Navigation/TopBar'
export type { TopBarProps, TopBarTab } from './components/Navigation/TopBar'

export { ActionTile } from './components/Overview/ActionTile'
export type { ActionTileProps } from './components/Overview/ActionTile'
export { Avatar } from './components/Overview/Avatar'
export type { AvatarProps } from './components/Overview/Avatar'
export { BadgeCard } from './components/Overview/BadgeCard'
export type { BadgeCardProps, BadgeCardTone } from './components/Overview/BadgeCard'
export { DailyBarsChart } from './components/Overview/DailyBarsChart'
export type { DailyBarsChartProps, DailyBar } from './components/Overview/DailyBarsChart'
export { HeaderActionCard, ProgressRow } from './components/Overview/HeaderActionCard'
export type {
  HeaderActionCardProps,
  ProgressRowProps,
  ProgressTone,
} from './components/Overview/HeaderActionCard'
export { PeriodTabs } from './components/Overview/PeriodTabs'
export type { PeriodTabsProps, PeriodTab } from './components/Overview/PeriodTabs'
export { PersonRow } from './components/Overview/PersonRow'
export type { PersonRowProps } from './components/Overview/PersonRow'
export { QuickActionsCard } from './components/Overview/QuickActionsCard'
export type { QuickActionsCardProps } from './components/Overview/QuickActionsCard'
export { ScreenBackground } from './components/Overview/ScreenBackground'
export type { ScreenBackgroundProps } from './components/Overview/ScreenBackground'
export { SectionBox } from './components/Overview/SectionBox'
export type { SectionBoxProps } from './components/Overview/SectionBox'
export { StatPair } from './components/Overview/StatPair'
export type { StatPairProps, StatPairItem } from './components/Overview/StatPair'

export { AccentCard } from './components/Pos/AccentCard'
export type { AccentCardProps } from './components/Pos/AccentCard'
export { ActionPanel } from './components/Pos/ActionPanel'
export type { ActionPanelProps } from './components/Pos/ActionPanel'
export { AmountDisplay } from './components/Pos/AmountDisplay'
export type { AmountDisplayProps } from './components/Pos/AmountDisplay'
export { CaptionButton } from './components/Pos/CaptionButton'
export type { CaptionButtonProps } from './components/Pos/CaptionButton'
export { CartCard, CartLine } from './components/Pos/CartCard'
export type { CartCardProps, CartLineProps } from './components/Pos/CartCard'
export { CategoryChip } from './components/Pos/CategoryChip'
export type { CategoryChipProps } from './components/Pos/CategoryChip'
export { ChangeAndPay } from './components/Pos/ChangeAndPay'
export type { ChangeAndPayProps } from './components/Pos/ChangeAndPay'
export { ChoiceCard } from './components/Pos/ChoiceCard'
export type { ChoiceCardProps } from './components/Pos/ChoiceCard'
export { ChoiceGroup } from './components/Pos/ChoiceGroup'
export type { ChoiceGroupProps, ChoiceOption } from './components/Pos/ChoiceGroup'
export { ConfirmSheet } from './components/Pos/ConfirmSheet'
export type { ConfirmSheetProps } from './components/Pos/ConfirmSheet'
export { CountedTotal } from './components/Pos/CountedTotal'
export type { CountedTotalProps } from './components/Pos/CountedTotal'
export { CountRow } from './components/Pos/CountRow'
export type { CountRowProps, CountRowTone } from './components/Pos/CountRow'
export { DenominationRow } from './components/Pos/DenominationRow'
export type { DenominationRowProps } from './components/Pos/DenominationRow'
export { GroupHeader } from './components/Pos/GroupHeader'
export type { GroupHeaderProps } from './components/Pos/GroupHeader'
export { InlineActions } from './components/Pos/InlineActions'
export type { InlineActionsProps, InlineAction } from './components/Pos/InlineActions'
export { InlineNotice } from './components/Pos/InlineNotice'
export type { InlineNoticeProps, InlineNoticeTone } from './components/Pos/InlineNotice'
export { Ledger } from './components/Pos/Ledger'
export type { LedgerProps, LedgerLine } from './components/Pos/Ledger'
export { MenuTile } from './components/Pos/MenuTile'
export type { MenuTileProps, MenuTileTone } from './components/Pos/MenuTile'
export { Numpad } from './components/Pos/Numpad'
export type { NumpadProps, NumpadVariant } from './components/Pos/Numpad'
export { PaymentBreakdown } from './components/Pos/PaymentBreakdown'
export type {
  PaymentBreakdownProps,
  PaymentBreakdownLine,
  PaymentBreakdownTone,
} from './components/Pos/PaymentBreakdown'
export { PaymentTabs } from './components/Pos/PaymentTabs'
export type { PaymentTabsProps, PaymentTab } from './components/Pos/PaymentTabs'
export { PinDots } from './components/Pos/PinDots'
export type { PinDotsProps } from './components/Pos/PinDots'
export { PosSearch } from './components/Pos/PosSearch'
export type { PosSearchProps } from './components/Pos/PosSearch'
export { ProductTile } from './components/Pos/ProductTile'
export type { ProductTileProps } from './components/Pos/ProductTile'
export { QuantityRow } from './components/Pos/QuantityRow'
export type { QuantityRowProps } from './components/Pos/QuantityRow'
export { QuickCash } from './components/Pos/QuickCash'
export type { QuickCashProps } from './components/Pos/QuickCash'
export { RequestCard } from './components/Pos/RequestCard'
export type { RequestCardProps, RequestCardTone } from './components/Pos/RequestCard'
export { StatusBar } from './components/Pos/StatusBar'
export type { StatusBarProps, StatusBadge, StatusTone, SandboxStrip } from './components/Pos/StatusBar'
export { StatusList } from './components/Pos/StatusList'
export type { StatusListProps, StatusLine, StatusLineTone } from './components/Pos/StatusList'
export { StatusModal, StatusModalLine } from './components/Pos/StatusModal'
export type {
  StatusModalProps,
  StatusModalLineProps,
  StatusModalTone,
} from './components/Pos/StatusModal'
export { StepsCompact } from './components/Pos/StepsCompact'
export type { StepsCompactProps, StepsCompactStep } from './components/Pos/StepsCompact'
export { TaskRow } from './components/Pos/TaskRow'
export type { TaskRowProps, TaskRowTone } from './components/Pos/TaskRow'
export { TotalCard } from './components/Pos/TotalCard'
export type { TotalCardProps, TotalCardRow } from './components/Pos/TotalCard'
export { VariantRow } from './components/Pos/VariantRow'
export type { VariantRowProps } from './components/Pos/VariantRow'

export type { IconProps } from './components/Icons/IconProps'
export { IconAlert } from './components/Icons/IconAlert'
export { IconBell } from './components/Icons/IconBell'
export { IconLogout } from './components/Icons/IconLogout'
export { IconMoon } from './components/Icons/IconMoon'
export { IconUser } from './components/Icons/IconUser'
export { IconCheck } from './components/Icons/IconCheck'
export { IconChevronLeft } from './components/Icons/IconChevronLeft'
export { IconChevronRight } from './components/Icons/IconChevronRight'
export { IconPencil } from './components/Icons/IconPencil'
export { IconPlus } from './components/Icons/IconPlus'
export { IconSearch } from './components/Icons/IconSearch'
export { IconSettings } from './components/Icons/IconSettings'
export { IconX } from './components/Icons/IconX'

export { AccountMenu } from './components/System/AccountMenu'
export type { AccountMenuProps, AccountMenuItem } from './components/System/AccountMenu'
export { Banner } from './components/System/Banner'
export type { BannerProps, BannerTone } from './components/System/Banner'
export { Divider } from './components/System/Divider'
export type { DividerProps } from './components/System/Divider'
export { ErrorPage } from './components/System/ErrorPage'
export type { ErrorPageProps, ErrorPageTone } from './components/System/ErrorPage'
export { FormDialog } from './components/System/FormDialog'
export type { FormDialogProps } from './components/System/FormDialog'
export { Kbd } from './components/System/Kbd'
export type { KbdProps } from './components/System/Kbd'
export { LoginCard } from './components/System/LoginCard'
export type { LoginCardProps } from './components/System/LoginCard'
export { SettingRow, SettingsList } from './components/System/SettingRow'
export type { SettingRowProps, SettingsListProps } from './components/System/SettingRow'
export { Spinner } from './components/System/Spinner'
export type { SpinnerProps, SpinnerSize } from './components/System/Spinner'
