// Vstupní bod knihovny. Komponenty se doplňují po vrstvách podle návrhu;
// zdrojem pravdy je docs/navrh v repozitářích aplikací (PNG + HTML export z Penu).
// Co tu není, pro aplikace neexistuje — nová komponenta se sem přidá ručně.

export { Button } from './components/Buttons/Button'
export type { ButtonProps, ButtonSize, ButtonVariant } from './components/Buttons/Button'
export { IconButton } from './components/Buttons/IconButton'
export type { IconButtonProps } from './components/Buttons/IconButton'

export { Calendar } from './components/Calendar/Calendar'
export type { CalendarProps, CalendarMode } from './components/Calendar/Calendar'
export { DatePresets } from './components/Calendar/DatePresets'
export type { DatePresetsProps, DatePresetOption } from './components/Calendar/DatePresets'
export { TimePicker } from './components/Calendar/TimePicker'
export type { TimePickerProps } from './components/Calendar/TimePicker'

export { Card } from './components/Cards/Card'
export type { CardProps } from './components/Cards/Card'
export { FloatingPill } from './components/Cards/FloatingPill'
export type { FloatingPillProps, FloatingPillVariant } from './components/Cards/FloatingPill'
export { GaugeCard } from './components/Cards/GaugeCard'
export type { GaugeCardProps, GaugeCardStat, GaugeCardTone } from './components/Cards/GaugeCard'
export { KeyValueList, KeyValueRow } from './components/Cards/KeyValueList'
export type { KeyValueListProps, KeyValueRowProps } from './components/Cards/KeyValueList'
export { StatCard } from './components/Cards/StatCard'
export type { StatCardProps, StatDelta } from './components/Cards/StatCard'
export { LabelPreview } from './components/Cards/LabelPreview'
export type { LabelPreviewProps } from './components/Cards/LabelPreview'
export { MediaCard } from './components/Cards/MediaCard'
export type { MediaCardProps } from './components/Cards/MediaCard'
export { NotificationItem, NotificationsPanel } from './components/Cards/NotificationsPanel'
export type {
  NotificationItemProps,
  NotificationsPanelProps,
  NotificationTone,
} from './components/Cards/NotificationsPanel'

export { BarChartHorizontal } from './components/Charts/BarChartHorizontal'
export type {
  BarChartHorizontalProps,
  BarChartHorizontalRow,
} from './components/Charts/BarChartHorizontal'
export { BarChartVertical } from './components/Charts/BarChartVertical'
export type {
  BarChartVerticalProps,
  BarChartVerticalBar,
} from './components/Charts/BarChartVertical'
export { ChartCard } from './components/Charts/ChartCard'
export type { ChartCardProps, ChartTone } from './components/Charts/ChartCard'
export { DonutChart } from './components/Charts/DonutChart'
export type { DonutChartProps, DonutSegment } from './components/Charts/DonutChart'
export { Sparkbars } from './components/Charts/Sparkbars'
export type { SparkbarsProps, SparkbarsBar } from './components/Charts/Sparkbars'
export { StackedBarChart } from './components/Charts/StackedBarChart'
export type {
  StackedBarChartProps,
  StackedBarGroup,
  StackedSegment,
} from './components/Charts/StackedBarChart'

export { Checkbox } from './components/Controls/Checkbox'
export type { CheckboxProps } from './components/Controls/Checkbox'
export { Chip, RemovableChip } from './components/Controls/Chip'
export type { ChipProps, ChipTone, RemovableChipProps } from './components/Controls/Chip'
export { Radio } from './components/Controls/Radio'
export type { RadioProps } from './components/Controls/Radio'
export { SegmentedControl } from './components/Controls/SegmentedControl'
export type { SegmentedControlProps, SegmentedOption } from './components/Controls/SegmentedControl'
export { Slider } from './components/Controls/Slider'
export type { SliderProps } from './components/Controls/Slider'
export { Switch } from './components/Controls/Switch'
export type { SwitchProps } from './components/Controls/Switch'

export { ActivityHeatmap } from './components/Data/ActivityHeatmap'
export type { ActivityHeatmapProps } from './components/Data/ActivityHeatmap'
export { FunnelChart } from './components/Data/FunnelChart'
export type { FunnelChartProps, FunnelStep } from './components/Data/FunnelChart'
export { KanbanCard, KanbanColumn } from './components/Data/KanbanColumn'
export type { KanbanCardProps, KanbanColumnProps, KanbanStatusTone } from './components/Data/KanbanColumn'
export { SegmentedProgress } from './components/Data/SegmentedProgress'
export type { ProgressSegment, SegmentedProgressProps, SegmentTone } from './components/Data/SegmentedProgress'
export { StatSparkCard } from './components/Data/StatSparkCard'
export type { StatSparkCardProps } from './components/Data/StatSparkCard'
export { TableEmpty } from './components/Data/TableEmpty'
export type { TableEmptyProps } from './components/Data/TableEmpty'
export type { TableStateColumn } from './components/Data/TableFrame'
export { TableLoading } from './components/Data/TableLoading'
export type { TableLoadingProps } from './components/Data/TableLoading'
export { Timeline, TimelineEvent } from './components/Data/Timeline'
export type { TimelineEventProps, TimelineProps, TimelineTone } from './components/Data/Timeline'

export { GroupedList } from './components/Lists/GroupedList'
export type { GroupedListProps } from './components/Lists/GroupedList'
export { ListRow } from './components/Lists/ListRow'
export type { ListRowProps, ListRowTone } from './components/Lists/ListRow'

export { Accordion, AccordionSection } from './components/Navigation/Accordion'
export type { AccordionProps, AccordionSectionProps } from './components/Navigation/Accordion'
export { Breadcrumbs } from './components/Navigation/Breadcrumbs'
export type { BreadcrumbsProps, BreadcrumbItem } from './components/Navigation/Breadcrumbs'
export { BulkActionBar } from './components/Navigation/BulkActionBar'
export type { BulkActionBarProps } from './components/Navigation/BulkActionBar'
export { CommandGroup, CommandItem, CommandPalette } from './components/Navigation/CommandPalette'
export type { CommandGroupProps, CommandItemProps, CommandPaletteProps } from './components/Navigation/CommandPalette'
export { PageHeader } from './components/Navigation/PageHeader'
export type { PageHeaderProps } from './components/Navigation/PageHeader'
export { Sidebar, SidebarGroup, SidebarItem } from './components/Navigation/Sidebar'
export type { SidebarGroupProps, SidebarItemProps, SidebarProps } from './components/Navigation/Sidebar'
export { Stepper } from './components/Navigation/Stepper'
export type { StepperProps, StepperStep } from './components/Navigation/Stepper'
export { TabsPill } from './components/Navigation/TabsPill'
export type { TabsPillItem, TabsPillProps } from './components/Navigation/TabsPill'
export { TabsUnderline } from './components/Navigation/TabsUnderline'
export type { TabsUnderlineProps, TabsUnderlineTab } from './components/Navigation/TabsUnderline'
export { ToolRail } from './components/Navigation/ToolRail'
export type { ToolRailProps, ToolRailItem } from './components/Navigation/ToolRail'
export { TopBar } from './components/Navigation/TopBar'
export type { TopBarProps, TopBarTab } from './components/Navigation/TopBar'

export { TreeItem, TreeView } from './components/Navigation/TreeView'
export type { TreeItemProps, TreeViewProps } from './components/Navigation/TreeView'

export { ConfirmDialog } from './components/Overlays/ConfirmDialog'
export type { ConfirmDialogProps, ConfirmDialogTone } from './components/Overlays/ConfirmDialog'
export { Drawer, DrawerRow } from './components/Overlays/Drawer'
export type { DrawerProps, DrawerRowProps } from './components/Overlays/Drawer'
export { Menu, MenuItem, MenuSeparator } from './components/Overlays/Menu'
export type { MenuItemProps, MenuProps, MenuSeparatorProps } from './components/Overlays/Menu'
export { SectionHeader } from './components/Overlays/SectionHeader'
export type { SectionHeaderProps } from './components/Overlays/SectionHeader'

export { ActionTile } from './components/Overview/ActionTile'
export type { ActionTileProps } from './components/Overview/ActionTile'
export { Avatar } from './components/Overview/Avatar'
export type { AvatarProps, AvatarStatus } from './components/Overview/Avatar'
export { AvatarStack } from './components/Overview/AvatarStack'
export type { AvatarStackProps, AvatarStackItem } from './components/Overview/AvatarStack'
export { BadgeCard } from './components/Overview/BadgeCard'
export type { BadgeCardProps, BadgeCardTone } from './components/Overview/BadgeCard'
export { DailyBarsChart } from './components/Overview/DailyBarsChart'
export type { DailyBarsChartProps, DailyBar } from './components/Overview/DailyBarsChart'
export { HeaderActionCard, ProgressRow } from './components/Overview/HeaderActionCard'
export type {
  HeaderActionCardProps,
  ProgressRowProps,
  ProgressTone,
} from './components/Overview/HeaderActionCard'
export { PeriodTabs } from './components/Overview/PeriodTabs'
export type { PeriodTabsProps, PeriodTab } from './components/Overview/PeriodTabs'
export { PersonRow } from './components/Overview/PersonRow'
export type { PersonRowProps } from './components/Overview/PersonRow'
export { QuickActionsCard } from './components/Overview/QuickActionsCard'
export type { QuickActionsCardProps } from './components/Overview/QuickActionsCard'
export { ScreenBackground } from './components/Overview/ScreenBackground'
export type { ScreenBackgroundProps } from './components/Overview/ScreenBackground'
export { SectionBox } from './components/Overview/SectionBox'
export type { SectionBoxProps } from './components/Overview/SectionBox'
export { StatPair } from './components/Overview/StatPair'
export type { StatPairProps, StatPairItem } from './components/Overview/StatPair'

export { AccentCard } from './components/Pos/AccentCard'
export type { AccentCardProps } from './components/Pos/AccentCard'
export { ActionPanel } from './components/Pos/ActionPanel'
export type { ActionPanelProps } from './components/Pos/ActionPanel'
export { AmountDisplay } from './components/Pos/AmountDisplay'
export type { AmountDisplayProps } from './components/Pos/AmountDisplay'
export { CaptionButton } from './components/Pos/CaptionButton'
export type { CaptionButtonProps } from './components/Pos/CaptionButton'
export { CartCard, CartLine } from './components/Pos/CartCard'
export type { CartCardProps, CartLineProps } from './components/Pos/CartCard'
export { CategoryChip } from './components/Pos/CategoryChip'
export type { CategoryChipProps } from './components/Pos/CategoryChip'
export { ChangeAndPay } from './components/Pos/ChangeAndPay'
export type { ChangeAndPayProps } from './components/Pos/ChangeAndPay'
export { ChoiceCard } from './components/Pos/ChoiceCard'
export type { ChoiceCardProps } from './components/Pos/ChoiceCard'
export { ChoiceGroup } from './components/Pos/ChoiceGroup'
export type { ChoiceGroupProps, ChoiceOption } from './components/Pos/ChoiceGroup'
export { ConfirmSheet } from './components/Pos/ConfirmSheet'
export type { ConfirmSheetProps } from './components/Pos/ConfirmSheet'
export { CountedTotal } from './components/Pos/CountedTotal'
export type { CountedTotalProps } from './components/Pos/CountedTotal'
export { CountRow } from './components/Pos/CountRow'
export type { CountRowProps, CountRowTone } from './components/Pos/CountRow'
export { DenominationRow } from './components/Pos/DenominationRow'
export type { DenominationRowProps } from './components/Pos/DenominationRow'
export { GroupHeader } from './components/Pos/GroupHeader'
export type { GroupHeaderProps } from './components/Pos/GroupHeader'
export { InlineActions } from './components/Pos/InlineActions'
export type { InlineActionsProps, InlineAction } from './components/Pos/InlineActions'
export { InlineNotice } from './components/Pos/InlineNotice'
export type { InlineNoticeProps, InlineNoticeTone } from './components/Pos/InlineNotice'
export { Ledger } from './components/Pos/Ledger'
export type { LedgerProps, LedgerLine } from './components/Pos/Ledger'
export { MenuTile } from './components/Pos/MenuTile'
export type { MenuTileProps, MenuTileTone } from './components/Pos/MenuTile'
export { Numpad } from './components/Pos/Numpad'
export type { NumpadProps, NumpadVariant } from './components/Pos/Numpad'
export { PaymentBreakdown } from './components/Pos/PaymentBreakdown'
export type {
  PaymentBreakdownProps,
  PaymentBreakdownLine,
  PaymentBreakdownTone,
} from './components/Pos/PaymentBreakdown'
export { PaymentTabs } from './components/Pos/PaymentTabs'
export type { PaymentTabsProps, PaymentTab } from './components/Pos/PaymentTabs'
export { PinDots } from './components/Pos/PinDots'
export type { PinDotsProps } from './components/Pos/PinDots'
export { PosSearch } from './components/Pos/PosSearch'
export type { PosSearchProps } from './components/Pos/PosSearch'
export { ProductTile } from './components/Pos/ProductTile'
export type { ProductTileProps } from './components/Pos/ProductTile'
export { QuantityRow } from './components/Pos/QuantityRow'
export type { QuantityRowProps } from './components/Pos/QuantityRow'
export { QuickCash } from './components/Pos/QuickCash'
export type { QuickCashProps } from './components/Pos/QuickCash'
export { RequestCard } from './components/Pos/RequestCard'
export type { RequestCardProps, RequestCardTone } from './components/Pos/RequestCard'
export { StatusBar } from './components/Pos/StatusBar'
export type { StatusBarProps, StatusBadge, StatusTone, SandboxStrip } from './components/Pos/StatusBar'
export { StatusList } from './components/Pos/StatusList'
export type { StatusListProps, StatusLine, StatusLineTone } from './components/Pos/StatusList'
export { StatusModal, StatusModalLine } from './components/Pos/StatusModal'
export type {
  StatusModalProps,
  StatusModalLineProps,
  StatusModalTone,
} from './components/Pos/StatusModal'
export { StepsCompact } from './components/Pos/StepsCompact'
export type { StepsCompactProps, StepsCompactStep } from './components/Pos/StepsCompact'
export { TaskRow } from './components/Pos/TaskRow'
export type { TaskRowProps, TaskRowTone } from './components/Pos/TaskRow'
export { TotalCard } from './components/Pos/TotalCard'
export type { TotalCardProps, TotalCardRow } from './components/Pos/TotalCard'
export { VariantRow } from './components/Pos/VariantRow'
export type { VariantRowProps } from './components/Pos/VariantRow'

export type { IconProps } from './components/Icons/IconProps'
export { Alert } from './components/Feedback/Alert'
export type { AlertProps, AlertTone } from './components/Feedback/Alert'
export { EmptyState } from './components/Feedback/EmptyState'
export type { EmptyStateProps } from './components/Feedback/EmptyState'
export { ProgressBar } from './components/Feedback/ProgressBar'
export type { ProgressBarProps, ProgressBarTone } from './components/Feedback/ProgressBar'
export { ProgressRing } from './components/Feedback/ProgressRing'
export type { ProgressRingProps, ProgressRingTone } from './components/Feedback/ProgressRing'
export { Skeleton, SkeletonList } from './components/Feedback/Skeleton'
export type { SkeletonProps, SkeletonListProps } from './components/Feedback/Skeleton'
export { Badge } from './components/Feedback/Badge'
export type { BadgeProps, BadgeTone } from './components/Feedback/Badge'
export { Toast } from './components/Feedback/Toast'
export type { ToastProps, ToastTone } from './components/Feedback/Toast'
export { Tooltip } from './components/Feedback/Tooltip'
export type { TooltipProps, TooltipVariant } from './components/Feedback/Tooltip'

export { Dropzone } from './components/Fields/Dropzone'
export type { DropzoneProps } from './components/Fields/Dropzone'
export type { FieldMenuOption } from './components/Fields/FieldMenu'
export { NumberStepper } from './components/Fields/NumberStepper'
export type { NumberStepperProps } from './components/Fields/NumberStepper'
export { SelectField } from './components/Fields/SelectField'
export type { SelectFieldProps } from './components/Fields/SelectField'
export { TextArea } from './components/Fields/TextArea'
export type { TextAreaProps } from './components/Fields/TextArea'
export { TextField } from './components/Fields/TextField'
export type { TextFieldProps } from './components/Fields/TextField'

export { Autocomplete } from './components/Forms/Autocomplete'
export type { AutocompleteProps } from './components/Forms/Autocomplete'
export { FileList, FileRow } from './components/Forms/FileList'
export type { FileListProps, FileRowProps } from './components/Forms/FileList'
export { MultiSelectField } from './components/Forms/MultiSelectField'
export type { MultiSelectFieldProps } from './components/Forms/MultiSelectField'
export { OtpField } from './components/Forms/OtpField'
export type { OtpFieldProps } from './components/Forms/OtpField'
export { PasswordField } from './components/Forms/PasswordField'
export type { PasswordFieldProps } from './components/Forms/PasswordField'
export { RangeSlider } from './components/Forms/RangeSlider'
export type { RangeSliderProps } from './components/Forms/RangeSlider'
export { Rating } from './components/Forms/Rating'
export type { RatingProps } from './components/Forms/Rating'

export { IconAlert } from './components/Icons/IconAlert'
export { IconCalendar } from './components/Icons/IconCalendar'
export { IconChevronDown } from './components/Icons/IconChevronDown'
export { IconEllipsis } from './components/Icons/IconEllipsis'
export { IconEye } from './components/Icons/IconEye'
export type { IconEyeProps } from './components/Icons/IconEye'
export { IconFile } from './components/Icons/IconFile'
export { IconMinus } from './components/Icons/IconMinus'
export { IconSort } from './components/Icons/IconSort'
export { IconStar } from './components/Icons/IconStar'
export type { IconStarProps } from './components/Icons/IconStar'
export { IconUpload } from './components/Icons/IconUpload'

export { IconArrowDown } from './components/Icons/IconArrowDown'
export { IconArrowUp } from './components/Icons/IconArrowUp'
export { IconBell } from './components/Icons/IconBell'
export { IconInfo } from './components/Icons/IconInfo'
export { IconLogout } from './components/Icons/IconLogout'
export { IconMoon } from './components/Icons/IconMoon'
export { IconUser } from './components/Icons/IconUser'
export { IconCheck } from './components/Icons/IconCheck'
export { IconChevronLeft } from './components/Icons/IconChevronLeft'
export { IconChevronRight } from './components/Icons/IconChevronRight'
export { IconPencil } from './components/Icons/IconPencil'
export { IconPlus } from './components/Icons/IconPlus'
export { IconSearch } from './components/Icons/IconSearch'
export { IconSettings } from './components/Icons/IconSettings'
export { IconX } from './components/Icons/IconX'

export { AccountMenu } from './components/System/AccountMenu'
export type { AccountMenuProps, AccountMenuItem } from './components/System/AccountMenu'
export { Banner } from './components/System/Banner'
export type { BannerProps, BannerTone } from './components/System/Banner'
export { Divider } from './components/System/Divider'
export type { DividerProps } from './components/System/Divider'
export { ErrorPage } from './components/System/ErrorPage'
export type { ErrorPageProps, ErrorPageTone } from './components/System/ErrorPage'
export { FormDialog } from './components/System/FormDialog'
export type { FormDialogProps } from './components/System/FormDialog'
export { Kbd } from './components/System/Kbd'
export type { KbdProps } from './components/System/Kbd'
export { LoginCard } from './components/System/LoginCard'
export type { LoginCardProps } from './components/System/LoginCard'
export { SettingRow, SettingsList } from './components/System/SettingRow'
export type { SettingRowProps, SettingsListProps } from './components/System/SettingRow'
export { Spinner } from './components/System/Spinner'
export type { SpinnerProps, SpinnerSize } from './components/System/Spinner'

export { DataTable, TableName, TableNumber } from './components/Table/DataTable'
export type {
  DataTableProps,
  DataTableColumn,
  DataTableRow,
  TableNameProps,
  TableNumberProps,
} from './components/Table/DataTable'
export { Pagination } from './components/Table/Pagination'
export type { PaginationProps } from './components/Table/Pagination'
export { TableSearch, TableToolbar } from './components/Table/TableToolbar'
export type { TableSearchProps, TableToolbarProps } from './components/Table/TableToolbar'
